project_id = "damitvvtyphjaeyvzyen"

[functions.generate-image-metadata]
verify_jwt = true

[functions.generate-blog]
verify_jwt = true

[functions.index-site-content]
verify_jwt = true

[functions.monitor-content-health]
verify_jwt = true

[functions.check-geo-location]
verify_jwt = false